# Generated by Django 4.1.2 on 2023-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_reply_parent_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='ai_generated_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='ai_generated_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
